# Generated by Django 5.2.15 on 2026-06-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("CANCELLED", "Cancelled"),
                    ("USED", "Used"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
