# Generated by Django 5.2.15 on 2026-06-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="amount",
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
