# Generated by Django 5.2.15 on 2026-06-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
