# Generated by Django 5.2.15 on 2026-06-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_wallettransaction_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAW", "Withdraw"),
                    ("REFUND", "Refund"),
                ],
                max_length=20,
            ),
        ),
    ]
