# Generated by Django 5.2.15 on 2026-06-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="citydistance",
            unique_together={("origin", "destination")},
        ),
    ]
