# Generated by Django 5.2.15 on 2026-06-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0002_systemsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="price_per_km",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price per kilometer",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="time_per_km",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Estimated time per kilometer (minutes)",
                max_digits=10,
            ),
        ),
    ]
