# Generated by Django 5.2.15 on 2026-06-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="travel_time_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
