# Generated by Django 5.2.15 on 2026-06-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
