# Generated by Django 5.2.15 on 2026-06-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_alter_trip_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
